#pragma once

#define DEFAULT_SCREEN_WIDTH	1060
#define DEFAULT_SCREEN_HEIGHT	680

#define RENDER_VIEWPORT_WIDTH 800
#define RENDER_VIEWPORT_HEIGHT 600

#define LABEL_LEFT			 (DEFAULT_SCREEN_WIDTH-220)
#define LABEL_TOP			 (DEFAULT_SCREEN_HEIGHT-40)
#define BUTTON_TOP			 60		 


